#!/bin/bash
#
# Test nbd device resizing. Regression test for patches "nbd: update size when
# connected" and "nbd: use bd_set_size when updating disk size".
#
# Copyright (C) 2018 Josef Bacik
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

. tests/nbd/rc

DESCRIPTION="resize a connected nbd device"
QUICK=1

requires() {
	_have_nbd && _have_program parted && _have_src_program nbdsetsize
}

test() {
	echo "Running ${TEST_NAME}"
	_start_nbd_server
	nbd-client -L -N export localhost /dev/nbd0 >> "$FULL" 2>&1
	parted -s /dev/nbd0 print 2>> "$FULL" | grep 'Disk /dev/nbd0'
	lsblk -n /dev/nbd0

	echo "Setting size to 1gib"
	src/nbdsetsize /dev/nbd0 1073741824

	lsblk -n /dev/nbd0
	parted -s /dev/nbd0 print 2>> "$FULL" | grep 'Disk /dev/nbd0'

	nbd-client -d /dev/nbd0 >> "$FULL" 2>&1
	_stop_nbd_server
}
