#!/bin/bash
# SPDX-License-Identifier: GPL-3.0+
# Copyright (C) 2018 Josef Bacik
#
# NBD tests.

. common/rc

group_requires() {
	_have_root && _have_nbd && modprobe nbd
}

_have_nbd() {
	if ! _have_modules nbd; then
		return 1
	fi
	if ! _have_program nbd-server; then
		return 1
	fi
	if ! _have_program nbd-client; then
		return 1
	fi
	if ! nbd-client --help 2>&1 | grep -q -- -L; then
		SKIP_REASON="nbd-client does not have -nonetlink/-L option"
		return 1
	fi
	return 0
}

_have_nbd_netlink() {
	if ! _have_nbd; then
		return 1
	fi
	if ! _have_program genl-ctrl-list; then
		return 1
	fi
	if ! genl-ctrl-list | grep -q nbd; then
		SKIP_REASON="nbd does not support netlink"
		return 1
	fi
	return 0
}

_wait_for_nbd_connect() {
	for ((i = 0; i < 3; i++)); do
		if [[ -e /sys/kernel/debug/nbd/nbd0/tasks ]]; then
			return 0
		fi
		sleep 1
	done
	return 1
}

_wait_for_nbd_disconnect() {
	for ((i = 0; i < 3; i++)); do
		if [[ ! -e /sys/kernel/debug/nbd/nbd0/tasks ]]; then
			return 0
		fi
		sleep 1
	done
	return 1
}

_start_nbd_server() {
	truncate -s 10G "${TMPDIR}/export"
	cat > "${TMPDIR}/nbd.conf" << EOF
[generic]
[export]
exportname=${TMPDIR}/export
EOF
	nbd-server -p "${TMPDIR}/nbd.pid" -C "${TMPDIR}/nbd.conf"
}

_stop_nbd_server() {
	kill -SIGTERM "$(cat "${TMPDIR}/nbd.pid")"
	rm -f "${TMPDIR}/nbd.pid"
	rm -f "${TMPDIR}/export"
}
