#!/bin/bash
#
# Regression test for commit 48ae8484e9fc ("scsi: sg: don't return bogus
# Sg_requests")
#
# Copyright (C) 2017 Johannes Thumshirn <jthumshirn@suse.de>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

. common/scsi_debug

DESCRIPTION="try triggering a kernel GPF with 0 byte SG reads"
QUICK=1

requires() {
	_have_src_program sg/syzkaller1
}

test_device() {
	echo "Running ${TEST_NAME}"

	SG_DEV="/dev/$(_get_sg_from_blockdev "$SCSI_DEBUG_NAME")"
	cd "$TMPDIR" || return 1
	timeout -s INT 10s "$SRCDIR/sg/syzkaller1" "$SG_DEV"

	echo "Test complete"
}
