#!/bin/bash
#
# Regression test for patch "scsi: sg: fix SG_DXFER_FROM_DEV transfers"
#
# Copyright (C) 2017 Johannes Thumshirn
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

DESCRIPTION="perfom a SG_DXFER_FROM_DEV from the /dev/sg read-write interface"
QUICK=1

requires() {
	_have_src_program sg/dxfer-from-dev
}

test_device() {
	echo "Running ${TEST_NAME}"

	SG_DEV="/dev/$(_get_test_dev_sg)"
	"$SRCDIR"/sg/dxfer-from-dev "$SG_DEV"

	echo "Test complete"
}
