#!/bin/bash
#
# Test loop device paritition scanning. Regression test for commit e02898b42380
# ("loop: fix LO_FLAGS_PARTSCAN hang").
#
# Copyright (C) 2017 Omar Sandoval
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

TEST_GROUPS=(loop auto quick)
DESCRIPTION="scan loop device partitions"

prepare() {
	_have_program parted
}

test() {
	echo "Running ${TEST_NAME}"

	truncate -s 1G "$TMPDIR/img"
	parted "$TMPDIR/img" --script \
		mklabel msdos \
		mkpart primary 0% 50% \
		mkpart primary 50% 100%

	loop_device="$(losetup -P -f --show "$TMPDIR/img")"
	lsblk -ln "$loop_device" | wc -l

	losetup -d "$loop_device"
	rm "$TMPDIR/img"
	echo "Test complete"
}
