#!/bin/bash
#
# Regression test for commit 6460495709ae ("Fix loop device flush before
# configure v3").
#
# Copyright (C) 2017 Omar Sandoval
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

. tests/loop/rc

DESCRIPTION="time opening and closing an unbound loop device"
QUICK=1

requires() {
	_have_src_program openclose
}

test() {
	echo "Running ${TEST_NAME}"

	# In a subshell so TIMEFORMAT doesn't get clobbered.
	(
	TIMEFORMAT="Test took %0R seconds"
	time src/openclose "$(losetup -f)" 5000
	)

	echo "Test complete"
}
