#!/bin/bash
# SPDX-License-Identifier: GPL-3.0+
# Copyright (C) 2017 Omar Sandoval
#
# Loop device tests.

. common/rc

group_requires() {
	_have_root && _have_loop
}

_have_loop_set_block_size() {
	src/loblksize "$(losetup -f)" 512 &>/dev/null
	if [[ $? -eq 2 ]]; then
		SKIP_REASON="kernel does not support LOOP_SET_BLOCK_SIZE"
		return 1
	fi
	return 0
}
