#!/bin/bash
# SPDX-License-Identifier: GPL-3.0+
# Copyright (C) 2023 Ziyang Zhang
#
# ublk tests.

. common/rc
. common/ublk
. common/fio

group_requires() {
	_have_root
	_have_ublk
	_have_fio
}

if which rublk > /dev/null 2>&1; then
	export UBLK_PROG="src/rublk_wrapper.sh"
else
	export UBLK_PROG="src/miniublk"
fi
