#!/bin/bash
# SPDX-License-Identifier: GPL-3.0+
# Copyright (C) 2018 Johannes Thumshirn
#
# Test nvme discovery with many subsystems so the discovery log page
# exceeds 4k

. tests/nvme/rc

DESCRIPTION="create many subsystems and test discovery"

requires() {
	_nvme_requires
	_have_modules loop
}

test() {
	echo "Running ${TEST_NAME}"

	_setup_nvmet

	local iterations=1000
	local port
	port="$(_create_nvmet_port "loop")"

	local loop_dev
	loop_dev="$(losetup -f)"

	for ((i = 0; i < iterations; i++)); do
		_create_nvmet_subsystem "blktests-subsystem-$i" "${loop_dev}"
		_add_nvmet_subsys_to_port "${port}" "blktests-subsystem-$i"
	done

	nvme discover -t loop | _filter_discovery

	for ((i = iterations - 1; i >= 0; i--)); do
		_remove_nvmet_subsystem_from_port "${port}" "blktests-subsystem-$i"
		_remove_nvmet_subsystem "blktests-subsystem-$i"
	done

	_remove_nvmet_port "${port}"

	echo "Test complete"
}
