#!/bin/bash
# SPDX-License-Identifier: GPL-3.0+
# Copyright (C) 2018 Johannes Thumshirn
#
# Regression test for commits d934f9848a77 ("nvme: provide UUID value to
# userspace") and 6484f5d16f9d ("nvme: also provide a UUID in the WWID sysfs
# attribute")

. tests/nvme/rc

DESCRIPTION="test nvme and nvmet UUID NS descriptors"
QUICK=1

requires() {
	_nvme_requires
	_have_loop
	_require_nvme_trtype_is_fabrics
}

test() {
	echo "Running ${TEST_NAME}"

	_setup_nvmet

	_nvmet_target_setup

	_nvme_connect_subsys

	local nvmedev
	nvmedev=$(_find_nvme_dev "${def_subsysnqn}")
	_check_uuid "${nvmedev}"

	_nvme_disconnect_subsys

	_nvmet_target_cleanup

	echo "Test complete"
}
