#!/bin/bash
# SPDX-License-Identifier: GPL-3.0+
# Copyright (C) 2018 Johannes Thumshirn
#
# Regression test for commits d934f9848a77 ("nvme: provide UUID value to
# userspace") and 6484f5d16f9d ("nvme: also provide a UUID in the WWID sysfs
# attribute")

. tests/nvme/rc

DESCRIPTION="test nvme and nvmet UUID NS descriptors"
QUICK=1

requires() {
	_nvme_requires
	_have_modules loop
}

test() {
	echo "Running ${TEST_NAME}"

	_setup_nvmet

	local port
	port="$(_create_nvmet_port "loop")"

	truncate -s 1G "$TMPDIR/img"

	local loop_dev
	loop_dev="$(losetup -f --show "$TMPDIR/img")"

	_create_nvmet_subsystem "blktests-subsystem-1" "${loop_dev}" \
		"91fdba0d-f87b-4c25-b80f-db7be1418b9e"
	_add_nvmet_subsys_to_port "${port}" "blktests-subsystem-1"

	nvme connect -t loop -n blktests-subsystem-1

	local nvmedev
	nvmedev="$(_find_nvme_loop_dev)"
	cat "/sys/block/${nvmedev}n1/uuid"
	cat "/sys/block/${nvmedev}n1/wwid"

	nvme disconnect -n "blktests-subsystem-1"
	_remove_nvmet_subsystem_from_port "${port}" "blktests-subsystem-1"
	_remove_nvmet_subsystem "blktests-subsystem-1"
	_remove_nvmet_port "${port}"
	losetup -d "$loop_dev"
	rm "$TMPDIR/img"

	echo "Test complete"
}
