#!/bin/bash
# SPDX-License-Identifier: GPL-2.0+
# Copyright (c) 2017-2018 Western Digital Corporation or its affiliates.
#
# Test NVMeOF target creation with a block device backed ns.

. tests/nvme/rc

DESCRIPTION="create an NVMeOF target with a block device-backed ns"
QUICK=1

requires() {
	_nvme_requires
	_have_modules loop
}

test() {
	echo "Running ${TEST_NAME}"

	local port
	local loop_dev
	local subsys_name="blktests-subsystem-1"

	_setup_nvmet

	truncate -s 1G "$TMPDIR/img"

	loop_dev="$(losetup -f --show "$TMPDIR/img")"

	_create_nvmet_subsystem "${subsys_name}" "${loop_dev}" \
		"91fdba0d-f87b-4c25-b80f-db7be1418b9e"
	port="$(_create_nvmet_port "loop")"
	_add_nvmet_subsys_to_port "${port}" "${subsys_name}"

	_remove_nvmet_subsystem_from_port "${port}" "${subsys_name}"
	_remove_nvmet_subsystem "${subsys_name}"
	_remove_nvmet_port "${port}"

	losetup -d "$loop_dev"

	rm "$TMPDIR/img"

	echo "Test complete"
}
