#!/bin/bash
# SPDX-License-Identifier: GPL-2.0+
# Copyright (c) 2017-2018 Western Digital Corporation or its affiliates.
#
# Test NVMeOF host creation with a block device backed ns.

. tests/nvme/rc

DESCRIPTION="create an NVMeOF host with a block device-backed ns"
QUICK=1

requires() {
	_nvme_requires
	_have_loop
	_require_nvme_trtype_is_fabrics
}

test() {
	echo "Running ${TEST_NAME}"

	_setup_nvmet

	local port
	local nvmedev

	port="$(_nvmet_target_setup --blkdev=device)"

	_nvme_connect_subsys "${nvme_trtype}" "${def_subsysnqn}"

	nvmedev=$(_find_nvme_dev "${def_subsysnqn}")
	cat "/sys/block/${nvmedev}n1/uuid"
	cat "/sys/block/${nvmedev}n1/wwid"

	udevadm settle

	_nvme_disconnect_subsys "${def_subsysnqn}"

	_nvmet_target_cleanup "${port}"

	echo "Test complete"
}
