#!/bin/bash
# SPDX-License-Identifier: GPL-2.0+
# Copyright (c) 2017-2018 Western Digital Corporation or its affiliates.
#
# Test mkfs with data verification for block device backed ns.

. tests/nvme/rc
. common/xfs

DESCRIPTION="run mkfs and data verification fio job on NVMeOF block device-backed ns"
TIMED=1

requires() {
	_nvme_requires
	_have_xfs
	_have_fio
	_have_loop
	_require_nvme_trtype_is_fabrics
	_require_nvme_test_img_size 350m
}

test() {
	echo "Running ${TEST_NAME}"

	_setup_nvmet

	local port
	local nvmedev
	local loop_dev

	truncate -s "${nvme_img_size}" "${def_file_path}"

	loop_dev="$(losetup -f --show "${def_file_path}")"

	_create_nvmet_subsystem "${def_subsysnqn}" "${loop_dev}" \
		"${def_subsys_uuid}"
	port="$(_create_nvmet_port "${nvme_trtype}")"
	_add_nvmet_subsys_to_port "${port}" "${def_subsysnqn}"

	_nvme_connect_subsys "${nvme_trtype}" "${def_subsysnqn}"

	nvmedev=$(_find_nvme_dev "${def_subsysnqn}")
	cat "/sys/block/${nvmedev}n1/uuid"
	cat "/sys/block/${nvmedev}n1/wwid"

	_xfs_run_fio_verify_io "/dev/${nvmedev}n1"

	_nvme_disconnect_subsys "${def_subsysnqn}"

	_remove_nvmet_subsystem_from_port "${port}" "${def_subsysnqn}"
	_remove_nvmet_subsystem "${def_subsysnqn}"
	_remove_nvmet_port "${port}"

	losetup -d "${loop_dev}"

	rm "${def_file_path}"

	echo "Test complete"
}
