#!/bin/bash
# SPDX-License-Identifier: GPL-2.0+
# Copyright (c) 2017-2018 Western Digital Corporation or its affiliates.
#
# Test mkfs with data verification for block device backed ns.

. tests/nvme/rc
. common/xfs

DESCRIPTION="run mkfs and data verification fio job on NVMeOF block device-backed ns"
TIMED=1

requires() {
	_nvme_requires
	_have_xfs
	_have_fio
	_have_loop
	_require_nvme_trtype_is_fabrics
	_require_nvme_test_img_size 350m
}

test() {
	echo "Running ${TEST_NAME}"

	_setup_nvmet

	local ns

	_nvmet_target_setup

	_nvme_connect_subsys

	ns=$(_find_nvme_ns "${def_subsys_uuid}")

	if ! _xfs_run_fio_verify_io "/dev/${ns}"; then
		echo "FAIL: fio verify failed"
	fi

	_nvme_disconnect_subsys

	_nvmet_target_cleanup

	echo "Test complete"
}
