#!/bin/bash
# SPDX-License-Identifier: GPL-2.0+
# Copyright (c) 2017-2018 Western Digital Corporation or its affiliates.
#
# Test NVMeOF flush command from host with a block device backed ns.

. tests/nvme/rc

DESCRIPTION="flush a NVMeOF block device-backed ns"
QUICK=1

requires() {
	_nvme_requires
	_have_loop
	_require_nvme_trtype_is_fabrics
}

set_conditions() {
	_set_nvme_trtype "$@"
}

test() {
	echo "Running ${TEST_NAME}"

	_setup_nvmet

	local ns
	local size
	local bs
	local count

	_nvmet_target_setup

	_nvme_connect_subsys

	ns=$(_find_nvme_ns "${def_subsys_uuid}")

	size="$(blockdev --getsize64 "/dev/${ns}")"
	bs="$(blockdev --getbsz "/dev/${ns}")"
	count=$((size / bs))

	dd if=/dev/urandom of="/dev/${ns}" \
		count="${count}" bs="${bs}" status=none

	nvme flush "/dev/${ns}"

	_nvme_disconnect_subsys

	_nvmet_target_cleanup

	echo "Test complete"
}
