#!/bin/bash
# SPDX-License-Identifier: GPL-2.0+
# Copyright (c) 2017-2018 Western Digital Corporation or its affiliates.
#
# Test many target bdev-ns creation/deletion under one subsystem.

. tests/nvme/rc

DESCRIPTION="create/delete many NVMeOF block device-backed ns and test discovery"

requires() {
	_nvme_requires
	_require_nvme_trtype_is_loop
}

test() {
	echo "Running ${TEST_NAME}"

	local port
	local iterations=1000
	local loop_dev
	local subsys_nqn="blktests-subsystem-1"

	_setup_nvmet

	loop_dev="$(losetup -f)"

	_create_nvmet_subsystem "${subsys_nqn}" "${loop_dev}"

	for ((i = 2; i <= iterations; i++)); do
		_create_nvmet_ns "${subsys_nqn}" "${i}" "${loop_dev}"
	done

	port="$(_create_nvmet_port "${nvme_trtype}")"
	_add_nvmet_subsys_to_port "$port" "${subsys_nqn}"

	_nvme_discover loop | _filter_discovery
	_remove_nvmet_subsystem_from_port "${port}" "${subsys_nqn}"
	_remove_nvmet_port "${port}"

	for ((i = iterations; i > 1; i--)); do
		_remove_nvmet_ns "${subsys_nqn}" "$i"
	done

	_remove_nvmet_subsystem "${subsys_nqn}"

	echo "Test complete"
}
