#!/bin/bash
# SPDX-License-Identifier: GPL-2.0+
# Copyright (c) 2017-2018 Western Digital Corporation or its affiliates.
#
# Test NVMe DSM Discard command on NVMeOF with a block-device ns.

. tests/nvme/rc

DESCRIPTION="test NVMe DSM Discard command on NVMeOF block-device ns"
QUICK=1

requires() {
	_nvme_requires
	_have_loop
	_require_nvme_trtype_is_fabrics
}

set_conditions() {
	_set_nvme_trtype "$@"
}

test() {
	echo "Running ${TEST_NAME}"

	_setup_nvmet

	local ns
	local nblk_range="10,10,10,10,10,10,10,10,10,10"
	local sblk_range="100,200,300,400,500,600,700,800,900,1000"

	_nvmet_target_setup

	_nvme_connect_subsys

	ns=$(_find_nvme_ns "${def_subsys_uuid}")
	nvme dsm "/dev/${ns}" --ad \
		--slbs "${sblk_range}" --blocks "${nblk_range}"

	_nvme_disconnect_subsys

	_nvmet_target_cleanup

	echo "Test complete"
}
