#!/bin/bash
# SPDX-License-Identifier: GPL-2.0+
# Copyright (c) 2017-2018 Western Digital Corporation or its affiliates.
#
# Test NVMe reset command.

. tests/nvme/rc

DESCRIPTION="test NVMe reset command"
QUICK=1

requires() {
	_nvme_requires
	_have_loop
	_require_nvme_trtype_is_fabrics
}

set_conditions() {
	_set_combined_conditions _set_nvme_trtype _set_nvmet_blkdev_type "$@"
}

test() {
	echo "Running ${TEST_NAME}"

	_setup_nvmet

	local nvmedev

	_nvmet_target_setup

	_nvme_connect_subsys

	nvmedev=$(_find_nvme_dev "${def_subsysnqn}")
	_check_uuid "${nvmedev}"

	if ! nvme reset "/dev/${nvmedev}" >> "$FULL" 2>&1; then
		echo "ERROR: reset failed"
	fi

	_nvme_disconnect_subsys >> "$FULL" 2>&1

	_nvmet_target_cleanup

	echo "Test complete"
}
