#!/bin/bash
# SPDX-License-Identifier: GPL-2.0+
# Copyright (c) 2017-2018 Western Digital Corporation or its affiliates.
#
# Test NVMe effects-log command on NVMeOF with a file-backed ns.

. tests/nvme/rc

DESCRIPTION="test NVMe effects-log command on NVMeOF file-backed ns"
QUICK=1

requires() {
	_nvme_requires
	_have_loop
	_require_nvme_trtype_is_fabrics
}

test() {
	echo "Running ${TEST_NAME}"

	_setup_nvmet

	local port
	local nvmedev

	truncate -s "${nvme_img_size}" "${def_file_path}"

	_create_nvmet_subsystem "${def_subsysnqn}" "${def_file_path}" \
		"${def_subsys_uuid}"
	port="$(_create_nvmet_port "${nvme_trtype}")"
	_add_nvmet_subsys_to_port "${port}" "${def_subsysnqn}"

	_nvme_connect_subsys "${nvme_trtype}" "${def_subsysnqn}"

	nvmedev=$(_find_nvme_dev "${def_subsysnqn}")
	cat "/sys/block/${nvmedev}n1/uuid"
	cat "/sys/block/${nvmedev}n1/wwid"

	if ! nvme effects-log "/dev/${nvmedev}" >> "$FULL" 2>&1; then
		echo "ERROR: effects-log failed"
	fi

	_nvme_disconnect_subsys "${def_subsysnqn}" >> "$FULL" 2>&1

	_remove_nvmet_subsystem_from_port "${port}" "${def_subsysnqn}"
	_remove_nvmet_subsystem "${def_subsysnqn}"
	_remove_nvmet_port "${port}"

	rm -f "${def_file_path}"

	echo "Test complete"
}
