#!/bin/bash
# SPDX-License-Identifier: GPL-2.0+
# Copyright (c) 2017-2018 Western Digital Corporation or its affiliates.
#
# Test NVMe list-subsys command on NVMeOF with a file-backed ns.

. tests/nvme/rc

DESCRIPTION="test NVMe list-subsys command on NVMeOF file-backed ns"
QUICK=1

requires() {
	_nvme_requires
	_have_loop
	_require_nvme_trtype_is_fabrics
}

set_conditions() {
	_set_nvme_trtype "$@"
}

test() {
	echo "Running ${TEST_NAME}"

	_setup_nvmet

	_nvmet_target_setup --blkdev file

	_nvme_connect_subsys

	if ! nvme list-subsys 2>> "$FULL" | grep -q "${nvme_trtype}"; then
		echo "ERROR: list-subsys"
	fi

	_nvme_disconnect_subsys >> "$FULL" 2>&1

	_nvmet_target_cleanup

	echo "Test complete"
}
