#!/bin/bash
# SPDX-License-Identifier: GPL-3.0+
# Copyright (C) 2019 Logan Gunthorpe
#
# Test nvme discovery generation counter

. tests/nvme/rc

DESCRIPTION="ensure the discovery generation counter is updated appropriately"
QUICK=1

requires() {
	_nvme_requires
	_have_loop
	_require_nvme_trtype_is_fabrics
}

set_conditions() {
	_set_nvme_trtype "$@"
}

test() {
	echo "Running ${TEST_NAME}"

	_setup_nvmet

	local port
	local genctr
	local subsys="blktests-subsystem-"

	port="$(_create_nvmet_port)"

	_create_nvmet_subsystem "${subsys}1" "$(losetup -f)"
	_add_nvmet_subsys_to_port "${port}" "${subsys}1"
	_create_nvmet_host "${subsys}1" "${def_hostnqn}"

	genctr=$(_discovery_genctr)

	_create_nvmet_subsystem "${subsys}2" "$(losetup -f)"
	_add_nvmet_subsys_to_port "${port}" "${subsys}2"

	genctr=$(_check_genctr "${genctr}" "adding a subsystem to a port")

	_add_nvmet_allow_hosts "${subsys}2" "${def_hostnqn}"

	genctr=$(_check_genctr "${genctr}" "adding host to allow_hosts")

	_remove_nvmet_allow_hosts "${subsys}2" "${def_hostnqn}"

	genctr=$(_check_genctr "${genctr}" "removing host from allow_hosts")

	_remove_nvmet_subsystem_from_port "${port}" "${subsys}2"
	_remove_nvmet_subsystem "${subsys}2"

	genctr=$(_check_genctr "${genctr}" "removing a subsystem from a port")

	_remove_nvmet_subsystem_from_port "${port}" "${subsys}1"
	_remove_nvmet_subsystem "${subsys}1"
	_remove_nvmet_port "${port}"
	_remove_nvmet_host "${def_hostnqn}"

	echo "Test complete"
}
