#!/bin/bash
# SPDX-License-Identifier: GPL-3.0+
# Copyright (C) 2019 Logan Gunthorpe
# Copyright (C) 2019 Eideticom Communications Inc.

. tests/nvme/rc

DESCRIPTION="run data verification fio job on an NVMeOF passthru controller"
TIMED=1

requires() {
	_nvme_requires
	_have_kernel_option NVME_TARGET_PASSTHRU
	_have_fio
}

test_device() {
	echo "Running ${TEST_NAME}"

	_setup_nvmet

	local ctrldev
	local nsdev
	local port

	port=$(_nvmet_passthru_target_setup "${def_subsysnqn}")
	nsdev=$(_nvmet_passthru_target_connect "${nvme_trtype}" "${def_subsysnqn}")

	_run_fio_verify_io --size="${nvme_img_size}" --filename="${nsdev}"

	_nvme_disconnect_subsys "${def_subsysnqn}"
	_nvmet_passthru_target_cleanup "${port}" "${def_subsysnqn}"

	echo "Test complete"
}
