#!/bin/bash
# SPDX-License-Identifier: GPL-3.0+
# Copyright (C) 2019 Logan Gunthorpe
# Copyright (C) 2019 Eideticom Communications Inc.

. tests/nvme/rc

DESCRIPTION="test NVMe reset command on an NVMeOF target with a passthru controller"
QUICK=1

requires() {
	_nvme_requires
	_have_kernel_option NVME_TARGET_PASSTHRU
}

test_device() {
	local subsys="blktests-subsystem-1"
	local ctrldev
	local port

	echo "Running ${TEST_NAME}"

	_setup_nvmet
	port=$(_nvmet_passthru_target_setup "${subsys}")
	nsdev=$(_nvmet_passthru_target_connect "${nvme_trtype}" "${subsys}")

	ctrldev=$(_find_nvme_dev "${subsys}")

	if ! nvme reset "/dev/${ctrldev}" >> "$FULL" 2>&1; then
		echo "ERROR: reset failed"
	fi

	_nvme_disconnect_subsys "${subsys}"
	_nvmet_passthru_target_cleanup "${port}" "${subsys}"

	echo "Test complete"
}
