#!/bin/bash
# SPDX-License-Identifier: GPL-3.0+
# Copyright (C) 2022 Sagi Grimberg <sagi@grimberg.me>
#
# Test nvme fabrics controller reset/disconnect/reconnect operation during I/O
# This test is somewhat similar to test 032 but for fabrics controllers.

. tests/nvme/rc

DESCRIPTION="test nvme fabrics controller reset/disconnect operation during I/O"

requires() {
	_nvme_requires
	_have_loop
	_have_fio
	_require_nvme_trtype_is_fabrics
}

test() {
	echo "Running ${TEST_NAME}"

	_setup_nvmet

	local port
	local loop_dev
	local nvmedev
	local fio_pid

	truncate -s "${nvme_img_size}" "${def_file_path}"
	loop_dev="$(losetup -f --show "${def_file_path}")"

	port="$(_create_nvmet_port "${nvme_trtype}")"
	_create_nvmet_subsystem "${def_subsysnqn}" "${loop_dev}"
	_add_nvmet_subsys_to_port "${port}" "${def_subsysnqn}"
	_nvme_connect_subsys "${nvme_trtype}" "${def_subsysnqn}"
	udevadm settle
	nvmedev=$(_find_nvme_dev "${def_subsysnqn}")

	# start fio job
	echo "starting background fio"
	_run_fio_rand_io --filename="/dev/${nvmedev}n1" \
		--group_reporting --ramp_time=5 \
		--time_based --runtime=1d &> /dev/null &
	fio_pid=$!
	sleep 5

	# do reset/remove operation
	echo "resetting controller"
	_nvme_reset_ctrl "${nvmedev}"
	sleep 1
	echo "deleting controller"
	_nvme_delete_ctrl "${nvmedev}"

	{ kill "${fio_pid}"; wait; } &> /dev/null

	_remove_nvmet_subsystem_from_port "${port}" "${def_subsysnqn}"
	_remove_nvmet_subsystem "${def_subsysnqn}"
	_remove_nvmet_port "${port}"

	losetup -d "${loop_dev}"

	rm -f "${def_file_path}"

	echo "Test complete"
}
