#!/bin/bash
# SPDX-License-Identifier: GPL-3.0+
# Copyright (C) 2022 Hannes Reinecke, SUSE Labs
#
# Test dhchap key types for authenticated connections

. tests/nvme/rc

DESCRIPTION="Test dhchap key types for authenticated connections"
QUICK=1

requires() {
	_nvme_requires
	_have_loop
	_have_kernel_option NVME_AUTH
	_have_kernel_option NVME_TARGET_AUTH
	_require_nvme_trtype_is_fabrics
	_require_nvme_cli_auth
}


test() {
	echo "Running ${TEST_NAME}"

	_setup_nvmet

	local port
	local hostid
	local hostnqn
	local file_path="${TMPDIR}/img"
	local hmac
	local key_len
	local hostkey
	local ctrldev

	hostid="${def_hostid}"
	hostnqn="${def_hostnqn}"

	truncate -s "${nvme_img_size}" "${file_path}"

	_create_nvmet_subsystem "${def_subsysnqn}" "${file_path}"
	port="$(_create_nvmet_port "${nvme_trtype}")"
	_add_nvmet_subsys_to_port "${port}" "${def_subsysnqn}"
	_create_nvmet_host "${def_subsysnqn}" "${hostnqn}"

	for hmac in 0 1 2 3; do
		echo "Testing hmac ${hmac}"
		hostkey="$(nvme gen-dhchap-key --hmac=${hmac} -n ${def_subsysnqn} 2> /dev/null)"
		if [ -z "$hostkey" ] ; then
			echo "couldn't generate host key for hmac ${hmac}"
			return 1
		fi
		_set_nvmet_hostkey "${hostnqn}" "${hostkey}"

		_nvme_connect_subsys "${nvme_trtype}" "${def_subsysnqn}" \
				     --hostnqn "${hostnqn}" \
				     --hostid "${hostid}" \
				     --dhchap-secret "${hostkey}"
		udevadm settle

		_nvme_disconnect_subsys "${def_subsysnqn}"
	done

	for key_len in 32 48 64; do
		echo "Testing key length ${key_len}"
		hostkey="$(nvme gen-dhchap-key --key-length=${key_len} -n ${def_subsysnqn} 2> /dev/null)"
		if [ -z "$hostkey" ] ; then
			echo "couldn't generate host key for length ${key_len}"
			return 1
		fi
		_set_nvmet_hostkey "${hostnqn}" "${hostkey}"

		_nvme_connect_subsys "${nvme_trtype}" "${def_subsysnqn}" \
				     --hostnqn "${hostnqn}" \
				     --hostid "${hostid}" \
				     --dhchap-secret "${hostkey}"

		udevadm settle

		_nvme_disconnect_subsys "${def_subsysnqn}"
	done

	_remove_nvmet_subsystem_from_port "${port}" "${def_subsysnqn}"
	_remove_nvmet_subsystem "${def_subsysnqn}"

	_remove_nvmet_port "${port}"

	_remove_nvmet_host "${hostnqn}"

	rm "${file_path}"

	echo "Test complete"
}
