#!/bin/bash
# SPDX-License-Identifier: GPL-3.0+
# Copyright (C) 2022 Hannes Reinecke, SUSE Labs
#
# Test bi-directional authentication

. tests/nvme/rc

DESCRIPTION="Test bi-directional authentication"
QUICK=1

requires() {
	_nvme_requires
	_have_loop
	_have_kernel_option NVME_AUTH
	_have_kernel_option NVME_TARGET_AUTH
	_require_nvme_trtype_is_fabrics
	_require_nvme_cli_auth
	_have_driver dh_generic
}


test() {
	echo "Running ${TEST_NAME}"

	_setup_nvmet

	local port
	local hostkey
	local ctrlkey
	local ctrldev

	hostkey="$(nvme gen-dhchap-key -n ${def_subsysnqn} 2> /dev/null)"
	if [ -z "$hostkey" ] ; then
		echo "failed to generate host key"
		return 1
	fi

	ctrlkey="$(nvme gen-dhchap-key -n ${def_subsysnqn} 2> /dev/null)"
	if [ -z "$ctrlkey" ] ; then
		echo "failed to generate ctrl key"
		return 1
	fi

	truncate -s "${nvme_img_size}" "${def_file_path}"

	_create_nvmet_subsystem "${def_subsysnqn}" "${def_file_path}"
	port="$(_create_nvmet_port "${nvme_trtype}")"
	_add_nvmet_subsys_to_port "${port}" "${def_subsysnqn}"
	_create_nvmet_host "${def_subsysnqn}" "${def_hostnqn}" \
			   "${hostkey}" "${ctrlkey}"

	_set_nvmet_dhgroup "${def_hostnqn}" "ffdhe2048"

	# Step 1: Connect with host authentication only
	echo "Test host authentication"
	_nvme_connect_subsys "${nvme_trtype}" "${def_subsysnqn}" \
			     --hostnqn "${def_hostnqn}" \
			     --hostid "${def_hostid}" \
			     --dhchap-secret "${hostkey}"

	_nvme_disconnect_subsys "${def_subsysnqn}"

	# Step 2: Connect with host authentication
	# and invalid ctrl authentication
	echo "Test invalid ctrl authentication (should fail)"
	_nvme_connect_subsys "${nvme_trtype}" "${def_subsysnqn}" \
			     --hostnqn "${def_hostnqn}" \
			     --hostid "${def_hostid}" \
			     --dhchap-secret "${hostkey}" \
			     --dhchap-ctrl-secret "${hostkey}"

	_nvme_disconnect_subsys "${def_subsysnqn}"

	# Step 3: Connect with host authentication
	# and valid ctrl authentication
	echo "Test valid ctrl authentication"
	_nvme_connect_subsys "${nvme_trtype}" "${def_subsysnqn}" \
			     --hostnqn "${def_hostnqn}" \
			     --hostid "${def_hostid}" \
			     --dhchap-secret "${hostkey}" \
			     --dhchap-ctrl-secret "${ctrlkey}"

	_nvme_disconnect_subsys "${def_subsysnqn}"

	# Step 4: Connect with host authentication
	# and invalid ctrl key
	echo "Test invalid ctrl key (should fail)"
	invkey="DHHC-1:00:Jc/My1o0qtLCWRp+sHhAVafdfaS7YQOMYhk9zSmlatobqB8C:"
	_nvme_connect_subsys "${nvme_trtype}" "${def_subsysnqn}" \
			     --hostnqn "${def_hostnqn}" \
			     --hostid "${def_hostid}" \
			     --dhchap-secret "${hostkey}" \
			     --dhchap-ctrl-secret "${invkey}"

	_nvme_disconnect_subsys "${def_subsysnqn}"

	_remove_nvmet_subsystem_from_port "${port}" "${def_subsysnqn}"
	_remove_nvmet_subsystem "${def_subsysnqn}"

	_remove_nvmet_port "${port}"

	_remove_nvmet_host "${def_hostnqn}"

	rm "${def_file_path}"

	echo "Test complete"
}
