#!/bin/bash
# SPDX-License-Identifier: GPL-3.0+
# Copyright (C) 2023 SUSE LLC
#
# Test if the fabrics transports are handling different queues types correctly.

. tests/nvme/rc
. common/xfs

DESCRIPTION="test different queue types for fabric transports"

requires() {
	_nvme_requires
	_have_xfs
	_have_fio
	_require_nvme_trtype tcp rdma
	_have_kver 4 21
}

test() {
	echo "Running ${TEST_NAME}"

	_setup_nvmet

	local port
	local nvmedev
	local loop_dev
	local rand_io_size

	truncate -s "${nvme_img_size}" "${def_file_path}"

	loop_dev="$(losetup -f --show "${def_file_path}")"

	_create_nvmet_subsystem "${def_subsysnqn}" "${loop_dev}" \
		"${def_subsys_uuid}"
	port="$(_create_nvmet_port "${nvme_trtype}")"
	_add_nvmet_subsys_to_port "${port}" "${def_subsysnqn}"

	_nvme_connect_subsys "${nvme_trtype}" "${def_subsysnqn}" \
		--nr-write-queues 1 || echo FAIL

	nvmedev=$(_find_nvme_dev "${def_subsysnqn}")

	rand_io_size="$(_nvme_calc_rand_io_size 4M)"
	_run_fio_rand_io --filename="/dev/${nvmedev}n1" --size="${rand_io_size}"

	_nvme_disconnect_subsys "${def_subsysnqn}" >> "$FULL" 2>&1

	_nvme_connect_subsys "${nvme_trtype}" "${def_subsysnqn}" \
		--nr-write-queues 1 \
		--nr-poll-queues 1 || echo FAIL

	_run_fio_rand_io --filename="/dev/${nvmedev}n1" --size="${rand_io_size}"

	_nvme_disconnect_subsys "${def_subsysnqn}" >> "$FULL" 2>&1

	_remove_nvmet_subsystem_from_port "${port}" "${def_subsysnqn}"
	_remove_nvmet_subsystem "${def_subsysnqn}"
	_remove_nvmet_port "${port}"

	losetup -d "${loop_dev}"

	rm "${def_file_path}"

	echo "Test complete"
}
