#!/bin/bash
#
# Test debugfs interaction with blktrace. Removes a device while blktrace is
# still running.
#
# Copyright (C) 2017 Omar Sandoval
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

. tests/block/rc
. common/scsi_debug

DESCRIPTION="remove a device while running blktrace"
QUICK=1

requires() {
	_have_blktrace && _have_scsi_debug
}

test() {
	echo "Running ${TEST_NAME}"

	if ! _init_scsi_debug; then
		return 1
	fi

	blktrace -D "$TMP_DIR" "/dev/${SCSI_DEBUG_DEVICES[0]}" >"$FULL" 2>&1 &
	sleep 0.5
	echo 1 > "/sys/block/${SCSI_DEBUG_DEVICES[0]}/device/delete"
	if [[ ! -d /sys/kernel/debug/block/${SCSI_DEBUG_DEVICES[0]} ]]; then
		echo "debugfs directory deleted with blktrace active"
	fi
	{ kill $!; wait; } >/dev/null 2>/dev/null
	if [[ -d /sys/kernel/debug/block/${SCSI_DEBUG_DEVICES[0]} ]]; then
		echo "debugfs directory leaked"
	fi

	_exit_scsi_debug

	echo "Test complete"
}
