#!/bin/bash
#
# Run a range of discards on a device, anywhere from 4k to 4g
#
# Copyright (C) 2017 Jens Axboe
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

DESCRIPTION="run various discard sizes"
TIMED=1

requires() {
	_have_fio
}

device_requires() {
	_test_dev_can_discard
}

test_device() {
	echo "Running ${TEST_NAME}"

	FIO_PERF_FIELDS=("trim iops")
	_fio_perf --bsrange=4k-4g --rw=randtrim --norandommap --name=discards \
		--filename="$TEST_DEV" --number_ios=200k

	echo "Test complete"
}
