#!/bin/bash
#
# Run a flush intensive workload
#
# Copyright (C) 2017 Jens Axboe
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

TEST_GROUPS=(block auto flush)

prepare() {
	_have_fio
}

test_device() {
	echo "Running ${TEST_NAME}"

	fio --output-format=terse --bs=4k --rw=randwrite --norandommap \
		--fsync=1 --number_ios=256 --numjobs=64 --name=flushes \
		--group_reporting=1 --filename="$TEST_DEV" >>"$FULL"

	TERSE_VER=$(cat $FULL | cut -d ';' -f1)
	if [[ "$TERSE_VER" -eq "3" ]]; then
		TEST_RUN[iops]=$(cat $FULL | cut -d ';' -f49)
	fi

	echo "Test complete"
}
