#!/bin/bash
# SPDX-License-Identifier: GPL-3.0+
# Copyright (C) 2018 Omar Sandoval
#
# Smoke test blk-mq timeout handling with null-blk.

. tests/block/rc
. common/null_blk

DESCRIPTION="run null-blk with blk-mq and timeout injection configured"

requires() {
	_have_null_blk && _have_module_param null_blk timeout
}

test() {
	echo "Running ${TEST_NAME}"

	# The format is "<interval>,<probability>,<space>,<times>". Here, we
	# fail 50% of I/Os.
	if ! _init_null_blk queue_mode=2 timeout='1,50,0,-1'; then
		return 1
	fi

	local scheds
	# shellcheck disable=SC2207
	scheds=($(sed 's/[][]//g' /sys/block/nullb0/queue/scheduler))

	for sched in "${scheds[@]}"; do
		echo "Testing $sched" >> "$FULL"
		echo "$sched" > /sys/block/nullb0/queue/scheduler
		# Do a bunch of I/Os which will timeout and then complete. The
		# only thing we're really testing here is that this doesn't
		# crash or hang.
		for ((i = 0; i < 100; i++)); do
			dd if=/dev/nullb0 of=/dev/null bs=4K count=4 \
				iflag=direct status=none &
		done
		wait
	done

	_exit_null_blk

	echo "Test complete"
}
