#!/bin/bash
#
# Test the iostats counters for time spent doing I/O.
#
# Copyright (C) 2018 Omar Sandoval
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

. tests/block/rc

DESCRIPTION="do I/O and check iostats times"
QUICK=1

requires() {
	_have_module null_blk
}

init_times() {
	init_read_ms="$(awk '{ print $4 }' /sys/block/nullb0/stat)"
	init_write_ms="$(awk '{ print $8 }' /sys/block/nullb0/stat)"
}

show_times() {
	read_ms="$(awk '{ print $4 }' /sys/block/nullb0/stat)"
	write_ms="$(awk '{ print $8 }' /sys/block/nullb0/stat)"

	# Print rounded to the nearest second
	printf 'read %d s\n' $(((read_ms - init_read_ms + 500) / 1000))
	printf 'write %d s\n' $(((write_ms - init_write_ms + 500) / 1000))
}

test() {
	echo "Running ${TEST_NAME}"

	for ((queue_mode = 1; queue_mode <= 2; queue_mode++)) do
		local init_read_ms init_write_ms read_ms write_ms

		echo "queue mode $queue_mode"

		modprobe -r null_blk
		modprobe null_blk queue_mode="$queue_mode" irqmode=2 \
			completion_nsec=1000000000 || continue

		udevadm settle

		init_times
		show_times

		dd if=/dev/nullb0 of=/dev/null bs=4096 iflag=direct count=1 status=none
		show_times

		dd if=/dev/zero of=/dev/nullb0 bs=4096 oflag=direct count=1 status=none
		show_times

		dd if=/dev/nullb0 of=/dev/null bs=4096 iflag=direct count=1 status=none &
		dd if=/dev/zero of=/dev/nullb0 bs=4096 oflag=direct count=1 status=none &
		dd if=/dev/zero of=/dev/nullb0 bs=4096 oflag=direct count=1 status=none &
		wait
		show_times

		modprobe -r null_blk

		unset init_read_ms init_write_ms read_ms write_ms
	done

	echo "Test complete"
}
