#!/bin/bash
# SPDX-License-Identifier: GPL-3.0+
# Copyright (C) 2017 Johannes Thumshirn <jthumshirn@suse.de>
#
# Regression test for commit 48ae8484e9fc ("scsi: sg: don't return bogus
# Sg_requests")

. tests/scsi/rc

DESCRIPTION="try triggering a kernel GPF with 0 byte SG reads"
QUICK=1

requires() {
	_have_scsi_generic && _have_src_program sg/syzkaller1
}

test_device() {
	echo "Running ${TEST_NAME}"

	SG_DEV="/dev/$(_get_test_dev_sg)"
	cd "$TMPDIR" || return 1
	timeout -s INT 10s "$SRCDIR/sg/syzkaller1" "$SG_DEV"

	echo "Test complete"
}
