#!/bin/bash
#
# Regression tests for SCSI generic device
#
# Copyright (C) 2017 Johannes Thumshirn <jthumshirn@suse.de>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

. common/rc

group_requires() {
	_have_root
}

group_device_requires() {
	_test_dev_is_scsi
}

_have_scsi_generic() {
	_have_module sg
}

_test_dev_is_scsi() {
	if [[ ! -d ${TEST_DEV_SYSFS}/device/scsi_device ]]; then
		SKIP_REASON="$TEST_DEV is not a SCSI device"
		return 1
	fi
	return 0
}

_test_dev_is_scsi_disk() {
	if [[ ! -d ${TEST_DEV_SYSFS}/device/scsi_disk ]]; then
		SKIP_REASON="$TEST_DEV is not a SCSI disk"
		return 1
	fi
	return 0
}

_get_test_dev_sg() {
	echo "${TEST_DEV_SYSFS}"/device/scsi_generic/sg* | grep -Eo "sg[0-9]+"
}
