#!/bin/bash
# SPDX-License-Identifier: GPL-3.0+
# Copyright (C) 2017 Johannes Thumshirn <jthumshirn@suse.de>
#
# Regression tests for SCSI generic device

. common/rc

group_requires() {
	_have_root
}

group_device_requires() {
	_require_test_dev_is_scsi
}

_have_scsi_generic() {
	_have_driver sg
}

_require_test_dev_is_scsi() {
	if [[ ! -d ${TEST_DEV_SYSFS}/device/scsi_device ]]; then
		SKIP_REASONS+=("$TEST_DEV is not a SCSI device")
		return 1
	fi
	return 0
}

_require_test_dev_is_scsi_disk() {
	if [[ ! -d ${TEST_DEV_SYSFS}/device/scsi_disk ]]; then
		SKIP_REASONS+=("$TEST_DEV is not a SCSI disk")
		return 1
	fi
	return 0
}

_get_test_dev_sg() {
	echo "${TEST_DEV_SYSFS}"/device/scsi_generic/sg* | grep -Eo "sg[0-9]+"
}

_test_dev_is_sata() {
	[[ $(<"${TEST_DEV_SYSFS}"/device/vendor) == "ATA     " ]]
}
