#!/bin/bash
# SPDX-License-Identifier: GPL-3.0+
# Copyright (C) 2017 Omar Sandoval
#
# Test a passing device test.

. tests/meta/rc

DESCRIPTION="do nothing"

test_device() {
	echo "Running ${TEST_NAME}"
	echo "Test complete"
}
