#!/bin/bash
# SPDX-License-Identifier: GPL-3.0+
# Copyright (C) 2017 Omar Sandoval
#
# Test a device test that fails with a non-zero exit status.

. tests/meta/rc

DESCRIPTION="exit with non-zero status"

test_device() {
	echo "Running ${TEST_NAME}"
	echo "Test complete"
	return 1
}
