#!/bin/bash
# SPDX-License-Identifier: GPL-3.0+
# Copyright (C) 2017 Omar Sandoval
#
# Test a test that fails with bad output.

. tests/meta/rc

DESCRIPTION="produce bad output"

test() {
	echo '¯\_(ツ)_/¯'
}
