#!/bin/bash
# SPDX-License-Identifier: GPL-3.0+
# Copyright (C) 2017 Omar Sandoval
#
# Test requires().

. tests/meta/rc

DESCRIPTION="skip in requires()"

requires() {
	SKIP_REASONS+=("(╯°□°)╯︵ ┻━┻")
}

test() {
	echo '¯\_(ツ)_/¯'
}
