#!/bin/bash
# SPDX-License-Identifier: GPL-3.0+
# Copyright (C) 2017 Omar Sandoval
#
# Test device_requires().

. tests/meta/rc

DESCRIPTION="skip in device_requires()"

device_requires() {
	SKIP_REASON="(╯°□°)╯︵ $TEST_DEV ┻━┻"
	return 1
}

test_device() {
	echo '¯\_(ツ)_/¯'
}
