#!/bin/bash
#
# Test filtering dmesg.
#
# Copyright (C) 2017 Omar Sandoval
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

. tests/meta/rc

DESCRIPTION="filter dmesg"
DMESG_FILTER="grep -v BUG"

requires() {
	_have_writeable_kmsg
}

test() {
	echo "Running ${TEST_NAME}"
	fake_bug_on
	echo "Test complete"
}
