#!/bin/bash
#
# null_blk helper functions.
#
# Copyright (C) 2017 Omar Sandoval
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

_have_null_blk() {
	_have_module null_blk
}

_init_null_blk() {
	if ! modprobe -r null_blk || ! modprobe null_blk "$@"; then
		return 1
	fi

	udevadm settle
	return 0
}

_exit_null_blk() {
	udevadm settle
	modprobe -r null_blk
}
