#!/bin/bash
#
# scsi_debug helper functions.
#
# Copyright (C) 2017 Omar Sandoval
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

_have_scsi_debug() {
	_have_module scsi_debug
}

_get_scsi_debug_dev() {
	modprobe -r scsi_debug
	if ! modprobe scsi_debug; then
		return 1
	fi

	udevadm settle

	local dev
	for dev in /sys/block/sd*; do
		if [[ "$(cat "${dev}/device/model")" =~ ^scsi_debug[[:space:]]*$ ]]; then
			SCSI_DEBUG_NAME="${dev#/sys/block}"
			SCSI_DEBUG_DEV="/dev/${SCSI_DEBUG_NAME}"
			return 0
		fi
	done

	echo "Could not get scsi_debug device" >&2
	return 1
}

_put_scsi_debug_dev() {
	modprobe -r scsi_debug
}
