#!/bin/bash
#
# SCSI generic helper functions.
#
# Copyright (C) 2017 Johannes Thumshirn
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

_have_scsi_generic() {
	_have_module sg
}

_test_dev_is_scsi() {
	if [[ ! -d ${TEST_DEV_SYSFS}/device/scsi_device ]]; then
		SKIP_REASON="$TEST_DEV is not a SCSI device"
		return 1
	fi
	return 0
}

_get_sg_from_blockdev() {
	echo /sys/block/"$1"/device/scsi_generic/sg+([0-9])
}
