#!/bin/bash
# SPDX-License-Identifier: GPL-3.0+
# Copyright (C) 2017 Omar Sandoval
#
# fio helper functions.

. common/shellcheck

_have_xfs() {
	_have_fs xfs && _have_program mkfs.xfs
}

_xfs_mkfs_and_mount() {
	local bdev=$1
	local mount_dir=$2

	mkdir -p "${mount_dir}"
	umount "${mount_dir}"
	mkfs.xfs -l size=32m -f "${bdev}"
	mount "${bdev}" "${mount_dir}"
}

_xfs_run_fio_verify_io() {
	local mount_dir="/mnt/blktests"
	local bdev=$1

	_xfs_mkfs_and_mount "${bdev}" "${mount_dir}" >> "${FULL}" 2>&1

	_run_fio_verify_io --size=950m --directory="${mount_dir}/"

	umount "${mount_dir}" >> "${FULL}" 2>&1
	rm -fr "${mount_dir}"
}
