#!/bin/bash
#
# Copyright (c) 2016-2018 Western Digital Corporation or its affiliates
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc.

. tests/srp/rc

DESCRIPTION="Direct I/O with large transfer sizes, cmd_sg_entries=1 and bs=8M"
QUICK=1

test_low_sg_size() {
	local dev m

	srp_login_params+=ch_count=1
	use_blk_mq y y "cmd_sg_entries=1" || return $?
	dev=$(get_bdev 0) || return $?
	run_fio --verify=md5 --rw=randwrite --bs=8M --loops=$((10**6)) \
		--iodepth=4 --group_reporting --sync=1 --direct=1 \
		--ioengine=libaio --size=${ramdisk_size} --runtime=10 \
		--filename="$dev" --name=low-sg-test --thread --numjobs=1 \
		--output="${RESULTS_DIR}/srp/fio-output-008.txt" >>"$FULL"
}

test() {
	trap 'trap "" EXIT; teardown' EXIT
	setup && test_low_sg_size && echo Passed
}
