#!/bin/bash
# SPDX-License-Identifier: GPL-2.0+
# Copyright (c) 2016-2018 Western Digital Corporation or its affiliates

. tests/srp/rc

DESCRIPTION="Direct I/O with large transfer sizes, cmd_sg_entries=1 and bs=8M"
QUICK=1

test_low_sg_size() {
	local dev m

	srp_login_params+=ch_count=1
	use_blk_mq y y "cmd_sg_entries=1" || return $?
	dev=$(get_bdev 0) || return $?
	run_fio --verify=md5 --rw=randwrite --bs=8M --loops=$((10**6)) \
		--iodepth=4 --group_reporting --sync=1 --direct=1 \
		--ioengine=libaio --size=${ramdisk_size} --runtime=10 \
		--filename="$dev" --name=low-sg-test --thread --numjobs=1 \
		--output="${RESULTS_DIR}/srp/fio-output-008.txt" >>"$FULL"
}

test() {
	trap 'trap "" EXIT; teardown' EXIT
	setup && test_low_sg_size && echo Passed
}
