#!/bin/bash
# SPDX-License-Identifier: GPL-2.0+
# Copyright (c) 2016-2018 Western Digital Corporation or its affiliates

. tests/srp/rc

DESCRIPTION="Buffered I/O with large transfer sizes, cmd_sg_entries=255 and bs=8M"
QUICK=1

test_large_transfer_size() {
	local dev m

	srp_login_params+=ch_count=1,queue_size=32,max_cmd_per_lun=32,max_sect=$((1<<17))
	use_blk_mq y y cmd_sg_entries=255 || return $?
	dev=$(get_bdev 0) || return $?
	run_fio --verify=md5 --rw=randwrite --bs=8M --loops=$((10**6)) \
		--iodepth=4 --group_reporting --sync=1 --direct=0 \
		--ioengine=libaio \
		--filename="$dev" --name=large-io-test --thread --numjobs=1 \
		--runtime=10 --output="${RESULTS_DIR}/srp/fio-output-010.txt" \
		>>"$FULL"
}

test() {
	trap 'trap "" EXIT; teardown' EXIT
	setup && test_large_transfer_size && echo Passed
}
