#!/bin/bash
#
# Copyright (c) 2016-2018 Western Digital Corporation or its affiliates
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc.

. tests/nvmeof-mp/rc

DESCRIPTION="Log in and log out"
QUICK=1

count_devices() {
	local d devs=0

	for d in /sys/class/nvme-fabrics/ctl/*/*/device; do
		[ -d "$d" ] && ((devs++))
	done
	echo $devs
}

wait_for_devices() {
	local expected=1 i devices

	use_blk_mq y || return $?
	for ((i=0;i<100;i++)); do
		devices=$(count_devices)
		[ "$devices" -ge $expected ] && break
		sleep .1
	done
	echo "count_devices(): $devices <> $expected" >>"$FULL"
	echo "count_devices(): $devices <> $expected"
	[ "$devices" -ge $expected ]
}

test() {
	trap 'trap "" EXIT; teardown' EXIT
	setup && wait_for_devices && echo Passed
}
