#!/bin/bash
# SPDX-License-Identifier: GPL-2.0+
# Copyright (c) 2016-2018 Western Digital Corporation or its affiliates

. tests/nvmeof-mp/rc

DESCRIPTION="Log in and log out"
QUICK=1

count_devices() {
	local d devs=0

	for d in /sys/class/nvme-fabrics/ctl/*/*/device; do
		[[ "$d" =~ hwmon[0-9]+|ng[0-9]+n[0-9]+ ]] && continue
		[ -d "$d" ] && ((devs++))
	done
	echo "$devs"
}

wait_for_devices() {
	local expected=1 i devices

	use_blk_mq y || return $?
	for ((i=0;i<100;i++)); do
		devices=$(count_devices)
		[ "$devices" -ge $expected ] && break
		sleep .1
	done
	echo "count_devices(): $devices <> $expected" >>"$FULL"
	echo "count_devices(): $devices <> $expected"
	[ "$devices" -ge $expected ]
}

test() {
	trap 'trap "" EXIT; teardown' EXIT
	setup && wait_for_devices && echo Passed
}
